Projekt/Projekt/urls.py
from django.contrib import admin
from django.urls import path, include
from pages import views #usunac po prezentacji
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts' : PostSitemap,
}

urlpatterns = [
    path('', views.home_view, name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projekt/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

Projekt/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

#jakbyscie mieli problem z tagami to zobaczcie ten post
# https://stackoverflow.com/questions/70497294/get-extra-restriction-missing-1-required-positional-argument-related-alias
class Post(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length = 150, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                                     related_name='blog_posts')
    image = models.ImageField(upload_to='images/')
    price= models.DecimalField(max_digits=10, decimal_places=2)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()

    class Meta:
        ordering = ('-price',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year,
                                                 self.publish.strftime("%m"),
                                                 self.publish.strftime("%d"),
                                                 self.slug])
    def get_rating(self):
        total = sum(int(review['stars']) for review in self.reviews.values())
        if self.reviews.count() > 0:
            return total / self.reviews.count()
        else:
            return 0

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name = 'comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return "Komentarz dodany przez {} dla posta {}".format(self.name, self.post)
    
class ProductReview(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name = 'reviews')
    user = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
    
    content = models.TextField(blank=True, null=True)
    stars = models.IntegerField()
    
    date_added = models.DateTimeField(auto_now_add=True)

Projekt/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('email','body')

Projekt/blog/views.py
from turtle import pos
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, ProductReview
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.views.generic import ListView
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count

# Create your views here.

#Pobieramy tag z domyslnym ustawieniem na None
def post_list(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 100)
    page = request.GET.get('page',1)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                 'blog/post/list.html',
                 {'page': page,
                  'posts': posts,
                  'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    comments = post.comments.filter(active = True)
    if request.method == 'POST' and request.user.is_authenticated:
        stars = request.POST.get('stars', 3)
        content = request.POST.get('content', '')

        review = ProductReview.objects.create(post=post, user=request.user, stars=stars, content=content)
        return redirect("blog:post_detail", year=year, month=month, day=day, post=post.slug)

    
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in = post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags = Count('tags')).order_by('-same_tags')[:8]
    return render(request,'blog/post/detail.html',{"post":post, 'comments':comments,'comment_form': comment_form,
                                                   "similar_posts":similar_posts})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sent = False
    if request.method == "POST":
        my_form = EmailPostForm(request.POST)
        if my_form.is_valid():
            my_form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            #trzeba bedzie dokonczyc subject, message itp
        else:
            my_form.errors
    else:
        my_form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': my_form,
                                                    'sent': sent})

    

Projekt/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{post.title}}{% endblock %}
{% block content %}
<hr class="my-4 text-dark">
<div class="bg-dark p-2 text-info bg-opacity-75 rounded-pill">
    <h2 class="display-2 text-white">{{post.title}}</h2>
    <div class="container text-white">
        <img src="{{post.image.url}}" height="100px" width="150px">
        <p>{{post.body}}</p>
        <h2 class="subtitle">Oceny: 
            {% if post.get_rating == 0 %}
                Brak ocen
            {% else %}
                {{ post.get_rating|floatformat:1 }}
            {% endif %}
        </h2>
        <p>Price: {{post.price}} $</p>
       
    </div>
    <p class="lead">
        <a href="{%url "blog:post_share" post.id %}">
            Udostepnij
        </a>
        
    </p>
</div>
<hr class="my-4 text-dark">
<div class="container-md bg-dark p-2 text-info bg-opacity-75" style="width:50%">
    <h4 class="text-white">Inne produkty</h4>
    {% for post in similar_posts %}
        <p class="mb-0">
            <a href =" {{ post.get_absolute_url }}"> {{post.title}}</a>
        </p>
        {% empty %}
            Poki co nie dodano podobnych pozycji.
        {% endfor %}
    {% with comments.count as total_comments %}
        <h6 class="text-white">
            {{ total_comments}} komentarz{{total_comments|pluralize:"y" }}
        </h6>
    {% endwith %}
    </div>
    <hr class="my-4 text-dark">
    {% for comment in comments %}
        <div class="bg-dark p-2 text-white bg-opacity-75">
            <p style="font-size: 1.5em">
            {{ comment.body }}
            </p>
            <p class = "text-white" style="font-size: 60%">
                Komentarz {{ forloop.counter }} dodany przez {{ comment.email }}
                {{ comment.created }} 
            </p>
        </div>
    {% empty %}
        <p class="text-white bg-dark opacity-75">Nie ma jeszcze komentarzy</p>
    {% endfor %}
    {% if new_comment %}
        <h2 class="display-6 text-white">Dodano komentarz</h2>
    {% else %}
        {% comment %} <h3 class="text-white bg-dark opacity-75 rounded-pill">Dodaj komentarz</h3>
        <div class="d-flex justify-content-center bg-dark p-2 text-info bg-opacity-75 rounded-pill">
        <form class="text-white" action="." method="POST">
            {{ comment_form.as_p}}
            {% csrf_token %}
            <p><input type="submit" value="Dodaj komentarz"></p>
        </form>
        </div> {% endcomment %}
    {% endif %}
    <hr class="my-4 text-dark">
    <h4 class="text-white bg-success">Oceny</h2>
            {% for review in post.reviews.all %}
                <div class="bg-success p-2 text-white bg-opacity-75 ">
                    <p style='text-white'>
                        <strong>Author </strong> {{review.user}} <br>
                        <strong>Date: </strong>{{ review.date_added|date:"Y-m-d" }} <br>
                        <strong>Stars: </strong>{{ review.stars }} <br>
                        {{ review.content }}
                    </p>
                </div>
                <hr class="my-4 text-dark">
            {% empty %}
                <div class="bg-success p-2 text-white bg-opacity-75">
                    Nie dodano jeszcze opinii.
                </div>
            {% endfor %}      
        <div class="bg-success p-2 text-white bg-opacity-75">
            {% if request.user.is_authenticated %}
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="text-dark" for="exampleFormControlSelect1">Stars: </label>
                        <select class='form-control' id="exampleFormControlSelect1" name="stars">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3" selected>3</option>
                            <option value="4">4</option>                          
                            <option value="5">5</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="text-dark" for="exampleFormControlTextarea1">Treść</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" name="content"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mb-2">Prześlij opinie</button>
                </form>

            {% else %}
                <div class="d-flex justify-content-center bg-dark p-2 text-info bg-opacity-75 rounded-pill">
                    <form class="text-white" action="." method="POST">
                        {{ comment_form.as_p}}
                        {% csrf_token %}
                        <p>
                            <input type="submit" value="Dodaj komentarz">
                        </p>
                    </form>
                </div>
            {% endif %}
        </div>
{% endblock %}

Projekt/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href = "{{ post.get_absolute_url }}"> {{ post.title }}</a>
            <p>{{post.publish}}</p>
        </li>
    {% endfor %}
</ul>

Projekt/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title%}Food Lovers {% endblock %}

{% block content %}
    <br>
    <h1 class="display-1 text-dark bg-white p-2 text-info bg-opacity-75">Ostatnie opinie</h1>
    <hr>
    {% for post in posts %}
    <div class="container">
    <div class="py-1 mb-2 bg-dark p-2 text-white bg-opacity-75 rounded-pill">
        <h5 class="display-5 text-success">
            <a href="{{ post.get_absolute_url }}">
                {{ post.title}}
                <img src="{{post.image.url}}" height="150px" width="150px">
            </a>
        </h5>
            <div class="container text-white" style="font-size:20px">
                {{ post.body|markdown|truncatewords_html:10 }}
                <hr class="my-4 text-danger">
            </div>
        
    
        <p class="tags">
            Firma: 
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {%endfor%}
        </p>
    </div>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

Projekt/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Udostepnij post{% endblock %}
{% block content %}
<br>
<div class="container bg-dark p-2 text-info bg-opacity-75 rounded">
     
        {% if sent %}
            <h1>Wiadomosc zostala wyslana</h1>
        {% else %}
            <h1 class="text-white">Udostepnij {{ post.title }}</h1>
            <div>
            <form class="form-horizontal text-justify text-white" action="." method="POST">
                <div class="text-justify text-white">
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" value="Wyslij wiadomosc e-mail">
                </div>
            </form>
        {% endif %}
{% endblock %}
</div>